"use client";
import { useEffect,useMemo,useState } from "react";
import type { Brawler,MapProfile } from "@/lib/types";
type Match={id:string;date:string;map:string;mode:string;brawler:string;result:'Victoria'|'Derrota';note:string};
export default function MatchTracker({maps,brawlers}:{maps:MapProfile[];brawlers:Brawler[]}){
 const key='brawl-lab:matches';const [matches,setMatches]=useState<Match[]>([]);const [map,setMap]=useState(maps[0].slug);const [brawler,setBrawler]=useState(brawlers[0].name);const [result,setResult]=useState<'Victoria'|'Derrota'>('Victoria');const [note,setNote]=useState('');
 useEffect(()=>{setMatches(JSON.parse(localStorage.getItem(key)||'[]'))},[]);
 const selected=maps.find(m=>m.slug===map)!;const save=()=>{const next=[{id:crypto.randomUUID(),date:new Date().toISOString(),map:selected.name,mode:selected.mode,brawler,result,note},...matches];localStorage.setItem(key,JSON.stringify(next));setMatches(next);setNote('')};
 const stats=useMemo(()=>{const wins=matches.filter(m=>m.result==='Victoria').length;return {games:matches.length,wins,rate:matches.length?Math.round(wins/matches.length*100):0}},[matches]);
 return <><div className="stats-grid"><div className="stat-card"><b>{stats.games}</b><span>partidas registradas</span></div><div className="stat-card"><b>{stats.wins}</b><span>victorias</span></div><div className="stat-card"><b>{stats.rate}%</b><span>win rate personal</span></div></div><div className="tracker-grid"><section className="panel"><h2>Registrar partida</h2><div className="form-grid"><label>Mapa<select value={map} onChange={e=>setMap(e.target.value)}>{maps.map(m=><option value={m.slug} key={m.slug}>{m.mode} · {m.name}</option>)}</select></label><label>Brawler<select value={brawler} onChange={e=>setBrawler(e.target.value)}>{brawlers.map(b=><option key={b.name}>{b.name}</option>)}</select></label><label>Resultado<select value={result} onChange={e=>setResult(e.target.value as typeof result)}><option>Victoria</option><option>Derrota</option></select></label><label>Nota<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Qué funcionó o falló"/></label></div><button className="primary-button" onClick={save}>Guardar partida</button></section><section className="panel"><h2>Historial local</h2><div className="match-list">{matches.slice(0,12).map(m=><article key={m.id}><span className={m.result==='Victoria'?'win':'loss'}>{m.result==='Victoria'?'V':'D'}</span><div><b>{m.brawler} · {m.map}</b><small>{m.mode}{m.note?` · ${m.note}`:''}</small></div></article>)}{!matches.length&&<div className="empty-state">Tus partidas se guardarán solo en este dispositivo.</div>}</div></section></div></>
}
